apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-demo
data:
  appsettings.k8s.json: |- 
    {

      "ConnectionStrings": {

        "DefaultConnection": "Server=mssql-deployment.default.svc.cluster.local;Database=mySQLDataBase;User Id=SA;Password=yourStrong(!)Password;"

      },

      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "Microsoft.AspNetCore": "Debug"

        }
      }
    }